### ISSUE TITLE
As a user I want my char pages to be styled in an appealing manner

### ISSUE THREAD

**Issue by MrStobbart** [MrStobbart/char-creator#15]
## Description

**Who** = As a user

**What** = I want the app to be styled in an appealing manner 

**Why** = so that I want to use it

## Subtasks

- [ ] Make it responsive (againg)
- [ ] Make uikit customizable and customize the following (and remove hack css classes)
- [ ] uk-for-controls: margin-left 145px
- [ ] uk-form-label: width: 130px
- [ ] .uk-form-label and label hack
- [ ] Make input fields more densed

## ACs

- [ ] The app looks great
