### ISSUE TITLE
Abstract localisation out of character class

### ISSUE THREAD

**Issue by MrStobbart** [MrStobbart/char-creator#23]
**Why** = to not have unnecessary information in the character class

## Detail information

- i18next could be used: https://www.i18next.com/overview/configuration-options

## Subtasks

- [x] Add localisation library to project
- [x] Remove labels from character class
- [x] update react components to use the localisation
