### ISSUE TITLE
Implement Autocomplet field

### ISSUE THREAD

**Issue by MrStobbart** [MrStobbart/char-creator#3]
## Description 
Available Libraries: 

https://react-select.com/home
https://jedwatson.github.io/react-select/
https://bundlephobia.com/result?p=react-select@2.1.1

## Subtasks

- [ ] Implement Backend
- [ ] Load qualities from the backend when charcreation page renders
- [ ] implement spinner if data is still being loaded
- [ ] use data for auto suggest field
