### ISSUE TITLE
Read talents and hindrances from rule file

### ISSUE THREAD

**Issue by MrStobbart** [MrStobbart/char-creator#5]
## Description

**Who** = As a developer

**What** = I want to automatically import new hindrances and talents from the rule file

**Why** = to not have to do it manually

## Detail information

Options for server:

- TypegraphQl
- GraphQL Nexus
- Apollo-server(-express)

### Technologie unrelated localisation strategy
- Use translation tables
	(+) Tables stay nice and readable
	(+) Data is always the same
	(-) I can't change the name of things if the name is the id
	(-) Translation tables can be very big and hard to maintain for big texts. Rendering the stuff online is probably harder
- Use an id column and then all the data from the files respectively
	(+) I can change all the data as long as the id stays the same
	(-) or (/) Rule files are not as nice readable when just exported as pdf (weird id column). This can be mitigated by showing the rules online and not rendering the id column.
	(-) It has to manually ensured that rules are the same between the translations

### Possible solutions for data

- Write all the files in markdown that can easily be parsed and shown. The editor Typora is great to edit tables.  -> We do this! 
	(+) Great Versioning 
	(+) One import, all data
	(-) It might be hard to bring custom styles
	(-) Not possible to have hidden fields in the tables
- Write markdown and the tables in different .csv
	(+) Great Versioning 
	(-) Import might be weird (lots of different .csv)
	(-) It might be hard to bring custom styles
	(-) Not possible to have hidden fields in the tables (maybe it is)
- Save data in database 
	(-) Not that great to edit
	(+) Nice way to save data
- Use google docs
	(+) Nice to api to access the data
	(-) Data stored online with google 
	( ) TODO: Can I use the api for everything (e.g. hidden fields)?
- Use .odt files
	(-) Import not that easy
	(-) Versioning weird
	(+) Great, easy to edit document

#### https://www.npmjs.com/package/markdown-tables-to-json

Headers were one of, but seems to work otherwise

#### https://www.npmjs.com/package/mdtable2json

Works better than the other ones

## Subtasks

- [x] Look for libraries
- [x] Import file
- [x] Use typecsript in the backend
- [x] Decide what to use as id and how to use the new rules
- [x] Write Endpoint for rules data (markdown + tables) - maybe some array that has two types of objects (md and references to table)
- [x] Write endpoint to get all the table data

## ACs

- [x] Talents and hindrances can automatically be imported
